#! /usr/bin/bash

createDatabaseFunc(){
    if [ -d Databases/$1 ]
    then
        echo Database already exists!
    else
        mkdir Databases/$1
        echo Database created sucessfully!
    fi
}