#! /usr/bin/bash
source ./createDatabaseFunc
source ./createTableFunc
createFunc() {
    if [[ $1 =~ ^[dD][aA][tT][aA][bB][aA][sS][eE]+$ ]]; then
        if [[ $# -ne 2 ]]; then
            echo 'Invalid number of arguments.'
        else
            if [[ -d Databases ]]
            then
            createDatabaseFunc ${@:2}
            else
            mkdir Databases
            createDatabaseFunc ${@:2}
            fi

        fi
    elif [[ $1 =~ ^[tT][aA][bB][lL][eE]+$ ]]; then
        if [[ $# -ne 3 ]]; then
            echo 'Invalid number of arguments.'
        else
        createTableFunc ${@:2}
        fi
    fi
}
