#! /usr/bin/bash
shopt -s extglob

# function for validating the input where you only want multiple arguments
funcValidationMI() {
    # echo $@ # debug
    errorFlag=1
    if [ $# -lt $(($1+1)) ]; then
        echo Invalid number of arguments
    elif [ -z $databaseInUse ]; then
        echo 'Please choose a database first!'
    elif [ ! -f $2 ] || [ ! -f $2'_metadata' ]; then
        echo "Specified table doesn't exist, Please create it first"
    else
        errorFlag=0
    fi
    return $errorFlag
}

# function for validating the input where you only want one argument
funcValidation() {
    # echo $@ # debug
    errorFlag=1
    if [ $# -ne $(($1+1)) ]; then
        echo Invalid number of arguments
    elif [ -z $databaseInUse ]; then
        echo 'Please choose a database first!'
    elif [ ! -f $2 ] || [ ! -f $2'_metadata' ]; then
        echo "Specified table doesn't exist, Please create it first"
    else
        errorFlag=0
    fi
    return $errorFlag
}