#! /usr/bin/bash

source ./createFunc
source ./useFunc
source ./renameDatabaseFunc
source ./dropDatabaseFunc
source ./listDatabasesFunc
source ./dropTableFunc
source ./insertIntoFunc
source ./truncateTableFunc
source ./showTablesFunc
source ./select
source ./delete
source ./updateFunc

shopt -s extglob
echo Welcome. Please choose a database mode.

select mode in MySQL Menu Exit; do
    case $mode in
    "MySQL")
        declare -i exit=0
        until [[ $exit -eq 1 ]]; do
            read -p "> " -a input
            case ${input[0]} in
            +([Ee][Xx][Ii][Tt]))
                exit
                ;;
            +([cC][rR][eE][aA][tT][eE]))
                createFunc ${input[@]:1}
                ;;
            +([uU][sS][eE]))
                if [[ $databaseInUse != "" ]]; then
                    cd ../..
                    useFuncSQL ${input[@]:1}
                    echo $databaseInUse
                else
                    useFuncSQL ${input[@]:1}
                fi
                ;;
            +([dD][rR][oO][pP]))
                if [[ ${input[1]} =~ ^[dD][aA][tT][aA][bB][aA][sS][eE]$ ]]; then
                    if [[ $databaseInUse != "" ]]; then
                        cd ../..
                        dropDatabaseFuncSQL ${input[@]:1}
                        if [[ $removedDatabase = $databaseInUse ]]; then
                            databaseInUse=""
                        else
                            cd Databases/$databaseInUse
                        fi

                    else
                        dropDatabaseFuncSQL ${input[@]:1}
                    fi
                elif [[ ${input[1]} =~ ^[tT][aA][bB][lL][eE]$ ]]; then
                    if [[ $databaseInUse != "" ]]; then
                        dropTableFuncSQL ${input[@]:1}
                    else
                        echo Please select a database first.
                    fi
                else
                    echo Invalid Syntax.
                fi
                ;;
            +([rR][eE][nN][aA][mM][eE]))
                if [[ $databaseInUse != "" ]]; then
                    cd ../..
                    renameDatabaseFuncSQL ${input[@]:1}
                    databaseInUse=$newDatabaseName
                    cd Databases/$databaseInUse
                else
                    renameDatabaseFuncSQL ${input[@]:1}
                fi
                ;;
            +([sS][hH][oO][wW]))
                if [[ ${input[1]} =~ ^[dD][aA][tT][aA][bB][aA][sS][eE][sS]$ ]]; then
                    if [[ $databaseInUse != "" ]]; then
                        cd ../..
                        listDatabasesFuncSQL ${input[@]:1}
                        cd Databases/$databaseInUse
                    else
                        listDatabasesFuncSQL ${input[@]:1}
                    fi
                elif [[ ${input[1]} =~ ^[tT][aA][bB][lL][eE][sS]$ ]]; then
                    if [[ $databaseInUse != "" ]]; then
                        showTablesFuncSQL ${input[@]:1}
                    else
                        echo Please select a database first.
                    fi
                fi
                ;;
            +([tT][rR][uU][nN][cC][aA][tT][eE]))
                if [[ ${input[1]} =~ ^[tT][aA][bB][lL][eE]$ ]]; then
                    if [[ $databaseInUse != "" ]]; then
                        truncateTableSQL ${input[@]:1}
                    else
                        echo Please select a database first.
                    fi
                fi
                ;;
            +([sS][eE][lL][eE][cC][tT]))
                if [[ $databaseInUse != "" ]]; then
                    selectSQL ${input[@]:1}
                else
                    echo Please select a database first.
                fi
                ;;
            +([dD][eE][lL][eE][tT][eE]))
                if [[ $databaseInUse != "" ]]; then
                    deleteSQL ${input[@]:1}
                else
                    echo Please select a database first.
                fi
                ;;
            +([Ii][Nn][Ss][Ee][Rr][Tt]))
                insertIntoFunc ${input[@]:1}
                ;;
            +([Uu][Pp][Dd][Aa][Tt][Ee]))
                updateFunc ${input[@]:1}
                ;;
            *)
                echo Invalid input.
                ;;
            esac
        done
        ;;
    "Menu")
        select option in "Select/Use Database" "Create Database" "Drop Database" "Rename Database" "Show Databases" "Create Table" "Insert Into Table" "Drop Table" "Truncate Table" "Show Tables" "Select Table" "Delete From Table" "Exit"; do
            case $option in
            "Select/Use Database")
                if [[ $databaseInUseMenu != "" ]]; then
                    cd ../..
                    useFunc
                    echo $databaseInUseMenu
                else
                    useFunc
                fi
                ;;
            "Create Database")
                echo create db
                ;;
            "Drop Database")
                if [[ $databaseInUseMenu != "" ]]; then
                    cd ../..
                    dropDatabaseFunc
                    if [[ $removedDatabaseMenu = $databaseInUseMenu ]]; then
                        databaseInUseMenu=""
                    else
                        cd Databases/$databaseInUseMenu
                    fi

                else
                    dropDatabaseFunc
                fi
                ;;
            "Rename Database")
                if [[ $databaseInUseMenu != "" ]]; then
                    cd ../..
                    renameDatabaseFunc
                    databaseInUseMenu=$newDatabaseNameMenu
                    cd Databases/$databaseInUseMenu
                else
                    renameDatabaseFunc
                fi
                ;;
            "Show Databases")
                if [[ $databaseInUseMenu != "" ]]; then
                    cd ../..
                    listDatabasesFunc
                    cd Databases/$databaseInUseMenu
                else
                    listDatabasesFunc
                fi
                ;;
            "Create Table")
                createTableWizard
                ;;
            "Insert Into Table")
                insertIntoWizard
                ;;
            "Drop Table")
                if [[ $databaseInUseMenu != "" ]]; then
                    dropTableFunc
                else
                    echo Please select a database first.
                fi
                ;;
            "Truncate Table")
                if [[ $databaseInUseMenu != "" ]]; then
                    truncateTable
                else
                    echo Please select a database first.
                fi
                ;;
            "Show Tables")
                if [[ $databaseInUseMenu != "" ]]; then
                    showTablesFunc
                else
                    echo Please select a database first.
                fi
                ;;
            "Select Table")
                if [[ $databaseInUseMenu != "" ]]; then
                    selectFunc
                else
                    echo Please select a database first.
                fi
                ;;
            "Delete From Table")
                if [[ $databaseInUseMenu != "" ]]; then
                    deleteFunc
                else
                    echo Please select a database first.
                fi
                ;;
            "Exit")
                exit
                ;;
            *)
                echo Invalid input
                ;;
            esac
        done
        ;;

    "Exit")
        exit
        ;;
    *)
        echo Invalid input.
        ;;
    esac
done
#echo $databaseInUse
