#! /usr/bin/bash

source ./createFunc
source ./useFunc
source ./renameDatabaseFunc
source ./dropDatabaseFunc
source ./listDatabasesFunc
source ./dropTableFunc

shopt -s extglob

declare -i exit=0
until [[ $exit -eq 1 ]]
do 
    read -p "> " -a input
    case ${input[0]} in
    +([Ee][Xx][Ii][Tt]))
        exit
        ;;
    +([cC][rR][eE][aA][tT][eE]))
        if [[ $databaseInUse != "" ]]
        then
            cd ../..
            createFunc ${input[@]:1}
            cd Databases/$databaseInUse
        else
            createFunc ${input[@]:1}
        fi
        
        ;;
    +([uU][sS][eE]))
        useFuncSQL ${input[@]:1}
        ;;
    +([dD][rR][oO][pP]))
    if [[ ${input[1]} =~ ^[dD][aA][tT][aA][bB][aA][sS][eE]$ ]]
    then
        if [[ $databaseInUse != "" ]]
        then
            cd ../..
            dropDatabaseFuncSQL ${input[@]:1}
                if [[ $removedDatabase = $databaseInUse ]]
                then
                    databaseInUse=""
                else
                    cd Databases/$databaseInUse
                fi

        else
            dropDatabaseFuncSQL ${input[@]:1}
        fi
    elif [[ ${input[1]} =~ ^[tT][aA][bB][lL][eE]$ ]]
    then
        if [[ $databaseInUse != "" ]]
        then
            dropTableFuncSQL ${input[@]:1} $databaseInUse
        else
            echo Please select a database first.
        fi
    else 
        echo Invalid Syntax.
    fi
    ;;
    +([rR][eE][nN][aA][mM][eE]))
        if [[ $databaseInUse != "" ]]
        then
            cd ../..
            renameDatabaseFuncSQL ${input[@]:1}
            databaseInUse=$newDatabaseName
            cd Databases/$databaseInUse
        else
            renameDatabaseFuncSQL ${input[@]:1}
        fi
        ;;
    +([sS][hH][oO][wW]))
        if [[ $databaseInUse != "" ]]
        then
            cd ../..
            listDatabasesFuncSQL ${input[@]:1}
            cd Databases/$databaseInUse
        else
            listDatabasesFuncSQL ${input[@]:1}
        fi
        ;;
    esac
done

#echo $databaseInUse