#! /usr/bin/bash
shopt -s extglob

useFuncSQL(){
    if [[ $# -ne 1 ]]
    then 
    echo Invalid number of arguments.
    else
        if [[ -e $1 ]]
        then
        cd $1
        echo Database $1 has been selected.
        databaseInUse=$1
        export $databaseInUse
        else
        echo Database $1 does not exist.
        fi
    fi
    
}

useFunc(){
    read -p "Please enter Database name: " name
    if [[ -e $name ]]
    then 
    cd $name 
    echo Database $name has been selected.
    else
    echo Database $name does not exist.
    fi
}

